#!/usr/bin/env bash
# 在 Debian 上安装 Incus，步骤和官方源完全相符：https://github.com/zabbly/incus

set -e

# 检查是否以 root 权限运行
if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run as root. Please use sudo or run as root."
    exit 1
fi

# 显示 GPG 密钥信息
curl -fsSL https://pkgs.zabbly.com/key.asc | gpg --show-keys --fingerprint

# 创建目录并下载密钥
mkdir -p /etc/apt/keyrings/
curl -fsSL https://pkgs.zabbly.com/key.asc -o /etc/apt/keyrings/zabbly.asc

# 添加 apt 源（Stable）
cat <<EOF >/etc/apt/sources.list.d/zabbly-incus-stable.sources
Enabled: yes
Types: deb
URIs: https://pkgs.zabbly.com/incus/stable
Suites: $(. /etc/os-release && echo ${VERSION_CODENAME})
Components: main
Architectures: $(dpkg --print-architecture)
Signed-By: /etc/apt/keyrings/zabbly.asc
EOF

# 更新软件包列表并安装 incus
apt-get update
apt-get install -y incus

echo "Incus installation completed"

echo "
To initialize Incus, please visit:
https://linuxcontainers.org/incus/docs/main/tutorial/first_steps/

To avoid using sudo with Incus, you can add your user to the incus-admin group.
Run the following command:

    sudo usermod -aG incus-admin $USER

After adding yourself to the group, you'll need to log out and log back in for the changes to take effect.
"
