#!/usr/bin/env bash

set -e

# 检查是否为 root 用户
if [ "$(id -u)" -eq 0 ]; then
    DOCKER_CMD="docker"
else
    DOCKER_CMD="sudo docker"
fi

# 检查 node_exporter 文件夹是否存在
if [ -d "node_exporter" ]; then
    echo "node_exporter directory already exists. Skipping creation."
else
    mkdir node_exporter
    echo "Created node_exporter directory."
fi

# 下载 docker-compose.yml 文件
curl -sSL https://raw.githubusercontent.com/Hentioe/dockerized-apps/master/node_exporter/docker-compose.yml -o node_exporter/docker-compose.yml
echo "Downloaded docker-compose.yml file."

# 在 node_exporter 文件夹中启动服务，但不改变当前目录
(
    cd node_exporter
    $DOCKER_CMD compose up -d
)

echo "Starting node_exporter. Displaying logs:"
$DOCKER_CMD compose -f node_exporter/docker-compose.yml logs -f
